### ISSUE TITLE
Why is the license copy-pasted from Minecraft Forge?

### ISSUE THREAD

**Issue by rfl890** [SlimingHD/LuckyTNTMod-1.19.3#18]
Maybe you should correct it?
[Here's a guide on how to use the LGPL if you want to](https://www.gnu.org/licenses/gpl-howto.html)

**Comment by SlimingHD** [comment]
Well, this license of forge comes shipped with the MDK, we just never bothered to remove it. We don't really intend on using any kind of special license. Should we just delete it?

**Comment by rfl890** [comment]
Deleting LICENSE.txt causes your work to be licensed under "All rights reserved" (which it probably already is, since the license is invalid in this context). For more information, see [here](https://choosealicense.com/no-permission/).

If you want a more open-source license style, try https://choosealicense.com/.

You can add a license from the web interface by going to this link: https://github.com/SlimingHD/LuckyTNTMod/community/license/new?branch=BRANCH_NAME_HERE,
replacing BRANCH_NAME_HERE with the branch you'd like to add the license to.
