### ISSUE TITLE
I made a simplified Chinese language package.

### ISSUE THREAD

**Issue by shenyx110** [SlimingHD/LuckyTNTMod-1.19.3#5]
I made a simplified Chinese language package.
[LuckyTNTMod.zip](https://github.com/SlimingHD/LuckyTNTMod/files/11746953/LuckyTNTMod.zip)

**Comment by SlimingHD** [comment]
Thank you very much! Please feel free to join our discord server, where you can chat with us and keep it updated better! We will incorporate it in our next update!
Join our discord through here: https://discord.gg/r2fNVSfNAA
